approved_skills:
  - skill_001_brave_search
  - skill_003_filesystem_read
  - skill_005_memory_kv
  - skill_041_royal_library

blocked_skills:
  - skill_999_experimental

fallback_rules:
  - if: skill_unavailable
    then: log_and_skip
  - if: rate_limit_exceeded
    then: exponential_backoff
